spring.application.name=subs-pruebas

server.port=8081

#Pruebas locales
spring.datasource.url=jdbc:oracle:thin:@//192.168.1.105:1521/XE
spring.datasource.username=abigail
spring.datasource.password=BISIM01
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

#Mostrar consultas en la consola
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.type=trace

# CORS LOCAL  y DEV.
cors.allowed-origins=http://localhost:4200, http://localhost:8080

# JWT
jwt.access-token-validity-ms=2700000
jwt.refresh-token-validity-ms=7200000

# Alaris
host.alaris=http://192.168.1.115:8080
API-Key=2cdbdb17-4d65-4fa0-b02a-b443879cd0c4
#API-Key=4644d3d0-9685-4ed4-b332-689c9f41ac68
Job-id=10030
Step-name=Classify
