spring.application.name=subs-pruebas

#Pruebas locales
spring.datasource.url=jdbc:oracle:thin:@//192.168.1.105:1521/XE
spring.datasource.username=abigail
spring.datasource.password=BISIM01
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.Oracle10gDialect

# Desarrollo Mostrar consultas en la consola
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.type=trace

# Desarrollo
cors.allowed-origins=http://localhost:4200, http://localhost:8080

# Producción (varios orígenes separados por coma)
# cors.allowed-origins=https://mifrontend.com,https://admin.mifrontend.com



# JWT
jwt.access-token-validity-ms=2700000
jwt.refresh-token-validity-ms=7200000